services:
  backend:
    platform: linux/amd64
    build:
      context: ./backend
    image: go-mnist
    container_name: go-mnist
    ports:
      - "8080:8080"
    volumes:
      - ./history:/app/history
    restart: unless-stopped

  frontend:
    platform: linux/amd64
    build:
      context: ./postcode-reader-web
    image: angular-mnist
    container_name: angular-mnist
    ports:
      - "4200:4200"
    restart: unless-stopped